apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod 
  labels: 
    app: nginx-pod-lbl
spec: 
  containers: 
    - name: nginx-cont 
      image: nginx:latest
      ports: 
        - containerPort: 80 
  restartPolicy: Always 

# kubectl apply -f nginx-pod.yaml