
---
apiVersion: apps/v1
kind: StatefulSet 
metadata: 
  name: postgres-app 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: postgres-app 
  template: 
    metadata: 
      labels: 
        app: postgres-app 
    spec: 
      containers: 
        - name: postgres-cont 
          image: postgres:14 
          env: 
            - name: POSTGRES_USER
              value: postgres # user name is : postgres
            - name: POSTGRES_DB
              valueFrom: 
                configMapKeyRef: 
                  name: postgres-configmap
                  key: POSTGRES_DB  
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: postgres-secret
                  key: MY_PASS
          volumeMounts: 
            - name: postgres-vol
              mountPath: /var/lib/postgresql/data
          ports: 
            - containerPort: 5432
  volumeClaimTemplates: 
        - metadata: 
            name: postgres-vol 
          spec: 
            accessModes: ["ReadWriteOnce"]
            storageClassName: nfs-client
            resources: 
              requests: 
                storage: 2Gi
# kubectl apply -f postgres-configmap.yaml
# kubectl apply -f postgres-secret.yaml
# kubectl apply -f postgres-statefulset.yaml

# for delete the old statefulset 
# kubectl delete -f postgres-statefulset.yaml
# kubectl apply -f postgres-svc.yaml



