services:
  base-postgres: 
    image: postgres:16-bullseye
    container_name: postgres-container
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
