# go templates
{{- if gt (int $.Values.replicas) 3 }}
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: {{ .Values.appName.app }}
spec: 
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:     
      # app: nginx-dpl
      {{- toYaml .Values.appName | nindent 6 }} 
  template: 
    metadata: 
      labels: 
        # app: nginx-deployment 
        {{- toYaml .Values.appName | nindent 7 }} 
    spec: 
      containers: 
        {{- with .Values.container }}
        - name: {{ .name }}
          image: {{ .image }}
          ports: 
          - containerPort: {{ .port }}
        {{- end }}
{{- else if le (int $.Values.replicas) 3  }}
  {{- fail "Replicas must be greater than 3 ! " }}
{{- end }}