---
- name: Second Project 
  hosts: master01 # localhost
  gather_facts: false
  vars_files:
    - vars.yml
  # vars: 
  #    database_username: postgres_user
  #    database_password: postgres2345
  tasks: 
    - name: Printing secret values 
      debug: 
        msg: "{{database_username}} and {{database_password}} "

# ansible-playbook -i inventory.ini playbooks/first-playbook.yml