# Prod : for the production 
--- 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata: 
  name: letsencrypt-prod 
  namespace: cert-manager
spec: 
  acme: 
     server: https://acme-v02.api.letsencrypt.org/directory
     email: lyvanna544@gmail.com
     privateKeySecretRef: 
        name: letsencrypt-prod
     solvers: 
      - http01: 
          ingress: 
             class: nginx 

# to get all avaiable api in k8s 
# kubectl api-resources