# Staging is for development purpose 
---
# Prod : for the production 
--- 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata: 
  name: letsencrypt-stage 
  namespace: cert-manager
spec: 
  acme: 
     server: https://acme-staging-v02.api.letsencrypt.org/directory
     email: lyvanna544@gmail.com
     privateKeySecretRef: 
        name: letsencrypt-stage
     solvers: 
      - http01: 
          ingress: 
             class: nginx 
# kubectl get clusterissuer