apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: web-app-green
  labels: 
    app: web-app-green
    replicas: green  
spec: 
  replicas: 4
  selector: 
    matchLabels: 
      app: web-app
      replicas: green 
  template: 
    metadata: 
      labels: 
        app: web-app
        replicas: green 
    spec: 
      containers: 
        - name: nginx-cont 
          image: 69966/reactjs-jenkins-nginx:v0.0.11
          ports: 
            - containerPort: 80
 
