apiVersion: v1
kind: Service
metadata: 
  name: spring-svc
spec: 
  # type: ClusterIP 
  type: NodePort
  selector: 
    app: spring-fileupload-dpl
  ports: 
    - name: spring-port 
      port: 8080
      targetPort: 8080 
      nodePort: 30000
