---
- name: First Playbook 
  hosts: workers
  become: true
#   options 
  tasks:
    # - name: Show working directory of worker 
    #   become_user: keo
    #   debug:    
    #     msg: "The directory is : {{ ansible_user_dir }}"
    - name: Create a file in home directory
      become: true  
      file: 
        path: "{{ansible_user_dir}}/whateveriti222s.txt"
        state: touch
    - name: Install nginx  and tree 
      apt: 
        name: 
            - nginx 
            - tree 
        state: present 
    # - name: Remove nginx from the system 
    #   apt: 
    #     name: nginx 
    #     state: absent


# ansible-playbook -i inventory.ini playbooks/first-playbook.yaml