#  target to worker02 
# -> create user , add that user to sudoer 
# tasks: -> install software  -> docker , docker compose , nginx 
---
- name: Install packages 
  hosts: 
    - worker02 
    # - master01
  become: true 
  tasks:
    - name: update and upgrade apt 
      apt: 
        update_cache: yes 
    - name: upgrade disk 
      apt: 
        upgrade: dist
    - name: remove unncessary packages 
      apt: 
        autoremove: yes

# To check if the syntax correct or not 
# ansible-playbook --syntax-check -i inventory.ini  playbooks/second-playbook.yaml 


# ansible-playbook -i inventory.ini playbooks/second-playbook.yaml