#  target to worker02 
# -> create user , add that user to sudoer 
# tasks: -> install software  -> docker , docker compose , nginx 
---
- import_playbook: ./first-playbook.yaml
- name: Install packages 
  hosts: 
    - worker02 
    # - master01
  become: true 
  vars: 
    worker_username: james
    worker_password: jamespassword
    ssh_public_key: "{{ lookup('file', '/home/keo/.ssh/id_rsa.pub') }}"  # Specify the path to your public key file

  tasks:

    - import_tasks: ../tasks/create-user.yaml
      when: false
    - name: Install nginx
      apt: 
        name:
          - nginx 
          - tree 
          - jq
          - neofetch
          - fd-find
        state: present
      # ignore_errors: yes
    - import_tasks: ../tasks/docker-setup.yaml
    - import_tasks: ../tasks/dc-deploy-reactjs.yaml
    
    # - name: Install docker after nginx 
    #   debug: 
    #     msg: "This is tasks after the first one "

# To check if the syntax correct or not 
# ansible-playbook --syntax-check -i inventory.ini  playbooks/second-playbook.yaml 


# ansible-playbook -i inventory.ini playbooks/second-playbook.yaml