#  target to worker02 
# -> create user , add that user to sudoer 
# tasks: -> install software  -> docker , docker compose , nginx 
---
- import_playbook: ./first-playbook.yaml
- name: Install packages 
  hosts: 
    - worker02 
    # - master01
  become: true 
  tasks:

    - import_tasks: ../tasks/create-user.yaml
    - name: Install nginx
      apt: 
        name:
          - nginx 
          - tree 
          - jq
          - neofetch
          - fd-find
        state: present
      # ignore_errors: yes
    - name: Install docker after nginx 
      debug: 
        msg: "This is tasks after the first one "

# To check if the syntax correct or not 
# ansible-playbook --syntax-check -i inventory.ini  playbooks/second-playbook.yaml 


# ansible-playbook -i inventory.ini playbooks/second-playbook.yaml