#  target to worker02 
# -> create user , add that user to sudoer 
# tasks: -> install software  -> docker , docker compose , nginx 
---
- name: Install packages 
  hosts: 
    - worker02 
    # - master01
  become: true 
  tasks:
    - name: update and upgrade apt 
      apt: 
        update_cache: yes 
    - name: upgrade disk 
      apt: 
        upgrade: dist
    - name: remove unncessary packages 
      apt: 
        autoremove: yes
    - name: Install nginx
      apt: 
        name:
          - nginx 
          - tree 
          - jq
          - neofetch
          - fd-find
        state: present
      # ignore_errors: yes
    - name: Install docker after nginx 
      debug: 
        msg: "This is tasks after the first one "

# To check if the syntax correct or not 
# ansible-playbook --syntax-check -i inventory.ini  playbooks/second-playbook.yaml 


# ansible-playbook -i inventory.ini playbooks/second-playbook.yaml