apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-pod-longhorn
spec:
  containers: 
   - name: web-server 
     image: nginx:alpine 
     volumeMounts: 
      - name: data-volume 
        mountPath: /usr/share/nginx/html 
  volumes: 
    - name: data-volume 
      persistentVolumeClaim: 
        claimName: my-demo-longhorn