apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: my-nginx-autoscaler
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-dpl
 minReplicas: 2
 maxReplicas: 10
#  configure metrics to scale up base on this 
 metrics:
 - type: Resource
   resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 1