apiVersion: v1
kind: Service 
metadata: 
  name: nginx-svc 
spec: 
  # type: ClusterIP 
  type: ClusterIP
  selector: 
    app: nginx-dpl
  ports: 
    - name: nginx-port 
      port: 80 
      targetPort: 80 
