Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "master3"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
  
  config.vm.synced_folder "../shared", "/vagrant_shared"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update 
    apt-get install -y fish 
    # read from the mounted directory 
    HOST_PUBLIC_KEY=$(cat /vagrant_shared/id_rsa.pub)
    mkdir -p /home/vagrant/.ssh
    echo "$HOST_PUBLIC_KEY" >> /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SHELL
end