 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: spring-pvc
spec: 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi
  # storageClassName: nfs-sharing
  # storageClassName: nfs-client
  storageClassName: nfs-client-retain # will use the retain claim policy 


# kubectl apply -f spring-pvc.yaml